;;; e2wm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from e2wm.el

(autoload 'e2wm:start-management "e2wm" "\
Setup e2wm window management for the current frame.

To force restart use the universal prefix argument (C-u) or
specify non-nil for FORCE-RESTART when calling as a lisp function.

When the perspective change function `e2wm:pst-change' is called
before executing this initialization function, this function
would be called at `e2wm:pst-change'. Then, NOT-PST-CHANGE is not
`nil' in order to prevent infinite looping.

(fn &optional PSTSET FORCE-RESTART NOT-PST-CHANGE)" t)
(register-definition-prefixes "e2wm" '("e2wm:"))


;;; Generated autoloads from e2wm-vcs.el

(autoload 'e2wm:dp-magit "e2wm-vcs" nil t)
(autoload 'e2wm:dp-monky "e2wm-vcs" nil t)
(autoload 'e2wm:dp-svn "e2wm-vcs" nil t)
(register-definition-prefixes "e2wm-vcs" '("e2wm:"))

;;; End of scraped data

(provide 'e2wm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; e2wm-autoloads.el ends here
