;;; exwm-edit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from exwm-edit.el

(autoload 'exwm-edit--compose "exwm-edit" "\
Edit text in an EXWM app.
If NO-COPY is non-nil, don't copy over the contents of the exwm text box

(fn &optional NO-COPY)" t)
(autoload 'exwm-edit--compose-minibuffer "exwm-edit" "\
Edit text in an EXWM app.
If COMPLETING-READ-ENTRIES is non-nil, feed that list into the collection
parameter of `completing-read'
If NO-COPY is non-nil, don't copy over the contents of the exwm text box

(fn &optional COMPLETING-READ-ENTRIES NO-COPY)" t)
(register-definition-prefixes "exwm-edit" '("exwm-edit-"))

;;; End of scraped data

(provide 'exwm-edit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; exwm-edit-autoloads.el ends here
