;;; org-hyperscheduler-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-hyperscheduler.el

(autoload 'org-hyperscheduler-open "org-hyperscheduler" "\
Open org-hyperscheduler in the browser." t)
(register-definition-prefixes "org-hyperscheduler" '("org-hyperscheduler-"))

;;; End of scraped data

(provide 'org-hyperscheduler-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-hyperscheduler-autoloads.el ends here
