;;; theme-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from modus-operandi-theme.el

(put 'modus-operandi 'theme-properties '(:background-mode light :kind color-scheme :family modus))


;;; Generated autoloads from modus-vivendi-theme.el

(put 'modus-vivendi 'theme-properties '(:background-mode dark :kind color-scheme :family modus))

;;; End of scraped data

(provide 'theme-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-loaddefs.el ends here
