;;; banner-comment-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from banner-comment.el

(autoload 'banner-comment "banner-comment" "\
Turn line at point into a banner comment.

Called on an existing banner comment, will reformat it.

Final column will be (or END-COLUMN comment-fill-column fill-column).

(fn &optional END-COLUMN)" t)
(register-definition-prefixes "banner-comment" '("banner-comment-"))

;;; End of scraped data

(provide 'banner-comment-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; banner-comment-autoloads.el ends here
