;;; jenkins-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from jenkins.el

(autoload 'jenkins "jenkins" "\
Initialize jenkins buffer." t)
(register-definition-prefixes "jenkins" '("*jenkins-jobs-list*" "get-jenkins-url" "jenkins-"))

;;; End of scraped data

(provide 'jenkins-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jenkins-autoloads.el ends here
