;;; pair-tree-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from pair-tree.el

(autoload 'pair-tree "pair-tree" "\
Draw a pair tree for PAIR.

(fn PAIR)" t)
(register-definition-prefixes "pair-tree" '("pair-tree-"))

;;; End of scraped data

(provide 'pair-tree-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pair-tree-autoloads.el ends here
