;;; exwm-x-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from exwmx-appconfig.el

(register-definition-prefixes "exwmx-appconfig" '("exwmx-appconfig"))


;;; Generated autoloads from exwmx-appmenu.el

(register-definition-prefixes "exwmx-appmenu" '("exwmx-appmenu"))


;;; Generated autoloads from exwmx-button.el

(register-definition-prefixes "exwmx-button" '("exwmx-button-"))


;;; Generated autoloads from exwmx-core.el

(register-definition-prefixes "exwmx-core" '("exwmx-"))


;;; Generated autoloads from exwmx-dmenu.el

(autoload 'exwmx-dmenu "exwmx-dmenu" "\
EXWM-X dynamic menu." t)
(autoload 'exwmx-dmenu-simple "exwmx-dmenu" "\
A simple version EXWM-X dynamic menu." t)
(register-definition-prefixes "exwmx-dmenu" '("exwmx-dmenu-"))


;;; Generated autoloads from exwmx-example.el

(register-definition-prefixes "exwmx-example" '("exwmx"))


;;; Generated autoloads from exwmx-floating.el

(register-definition-prefixes "exwmx-floating" '("exwmx-floating-"))


;;; Generated autoloads from exwmx-grocery.el

(register-definition-prefixes "exwmx-grocery" '("exwmx-grocery--"))


;;; Generated autoloads from exwmx-loader.el

(register-definition-prefixes "exwmx-loader" '("exwmx-default-example"))


;;; Generated autoloads from exwmx-quickrun.el

(register-definition-prefixes "exwmx-quickrun" '("exwmx-"))


;;; Generated autoloads from exwmx-sendstring.el

(register-definition-prefixes "exwmx-sendstring" '("exwmx-sendstring"))


;;; Generated autoloads from exwmx-xfce.el

(register-definition-prefixes "exwmx-xfce" '("exwmx-xfce-"))


;;; End of scraped data

(provide 'exwm-x-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; exwm-x-autoloads.el ends here
