;;; org-timeline-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from org-timeline.el

(autoload 'org-timeline-insert-timeline "org-timeline" "\
Insert graphical timeline into agenda buffer.")
(register-definition-prefixes "org-timeline" '("org-timeline-"))

;;; End of scraped data

(provide 'org-timeline-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-timeline-autoloads.el ends here
