;;; org-kanban-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-kanban.el

(autoload 'org-kanban/initialize "org-kanban" "\
Create an org-kanban dynamic block at position ARG.

(fn &optional ARG)" t)
(autoload 'org-kanban/initialize-at-beginning "org-kanban" "\
Create an org-kanban dynamic block at the beginning of the buffer." t)
(autoload 'org-kanban/initialize-at-end "org-kanban" "\
Create an org-kanban dynamic block at the end of the buffer." t)
(autoload 'org-kanban/initialize-here "org-kanban" "\
Create an org-kanban dynamic block at the point." t)
(autoload 'org-dblock-write:kanban "org-kanban" "\
Create the kanban dynamic block.
PARAMS may contain `:mirrored`, `:match`, `:scope`, `:layout`,
`:range`, `:depth` and `:compressed`.

(fn PARAMS)")
(autoload 'org-kanban/configure-block "org-kanban" "\
Configure the current org-kanban dynamic block." t)
(register-definition-prefixes "org-kanban" '("org-kanban"))

;;; End of scraped data

(provide 'org-kanban-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-kanban-autoloads.el ends here
